"""
IDA Form UI for the advanced search dialog.

Provides ``binary_search_form`` -- a modal ``idaapi.Form`` with:

- Pattern text input with live preview of generated byte patterns.
- Type specifier dropdown (``parse.Types``).
- Endian radio buttons (Little / Big / Both).
- Backend checkboxes (byte search, instruction operands, microcode,
  ctree, pseudocode text).  Hex-Rays backends are hidden when the
  decompiler is not available.
- Backend applicability notes in the preview area.

The form is opened by ``advanced_search_ah_t`` in ``plugin.py`` via
the ``Alt-Shift-B`` hotkey.  After ``Execute()`` returns 1 (OK), the
caller extracts the pattern string, endian, and backend bitmask
using ``get_pattern()``, ``get_endian()``, and ``get_backends_mask()``.

Backend bitmask bit indices are exported as module-level constants:
``BACKEND_BYTES``, ``BACKEND_INSN``, ``BACKEND_MICRO``,
``BACKEND_CTREE``, ``BACKEND_PSEUDO``.
Case sensitivity is controlled by a separate Options group box.
"""

import enum

import idaapi
import parse
from importlib import reload

reload(parse)
from parse import PatternCategory


def get_reqmat_choices() -> list[tuple[str, int]]:
    names = []
    for name in dir(idaapi):
        if not name.startswith("MMAT_"):
            continue
        value = getattr(idaapi, name, None)
        if isinstance(value, int):
            names.append((name, value))

    if not names:
        return [("MMAT_LOCOPT", 0)]

    return sorted(names, key=lambda item: (item[1], item[0]))


def default_reqmat() -> int:
    return getattr(idaapi, "MMAT_LOCOPT", get_reqmat_choices()[0][1])


def get_cmat_choices() -> list[tuple[str, int]]:
    names = []
    for name in dir(idaapi):
        if not name.startswith("CMAT_"):
            continue
        value = getattr(idaapi, name, None)
        if isinstance(value, int):
            names.append((name, value))

    if not names:
        return [("CMAT_FINAL", 0)]

    return sorted(names, key=lambda item: (item[1], item[0]))


def default_cmat() -> int:
    return getattr(idaapi, "CMAT_FINAL", get_cmat_choices()[0][1])


class callback_e(enum.IntEnum):
    CB_INIT = idaapi.CB_INIT
    CB_YES = idaapi.CB_YES
    CB_CLOSE = idaapi.CB_CLOSE
    CB_INVISIBLE = idaapi.CB_INVISIBLE
    CB_DESTROYING = idaapi.CB_DESTROYING
    CB_NO = idaapi.CB_NO
    CB_CANCEL = idaapi.CB_CANCEL


BACKEND_BYTES = 0
BACKEND_INSN = 1
BACKEND_MICRO = 2
BACKEND_CTREE = 3
BACKEND_PSEUDO = 4


class binary_search_form(idaapi.Form):
    """Form for entering a search pattern and selecting backends."""

    def __init__(
        self,
        default_query: str = "de ad be ef,h",
        backends_mask: int = 1,
        options_mask: int = 0,
        reqmat: int | None = None,
        cmat: int | None = None,
    ):
        F = idaapi.Form

        help_text = parse.help()
        overview = parse.html_overview()

        self._has_hexrays = idaapi.init_hexrays_plugin()
        self._reqmat_choices = get_reqmat_choices()
        self._reqmat_values = [value for _, value in self._reqmat_choices]
        initial_reqmat = default_reqmat() if reqmat is None else reqmat
        try:
            initial_reqmat_index = self._reqmat_values.index(initial_reqmat)
        except ValueError:
            initial_reqmat_index = 0
        self._cmat_choices = get_cmat_choices()
        self._cmat_values = [value for _, value in self._cmat_choices]
        initial_cmat = default_cmat() if cmat is None else cmat
        try:
            initial_cmat_index = self._cmat_values.index(initial_cmat)
        except ValueError:
            initial_cmat_index = 0

        F.__init__(
            self,
            rf"""STARTITEM 0
BUTTON YES* Search
BUTTON CANCEL Cancel
HELP
{help_text}
ENDHELP
IDA Search
{{FormChangeCb}}
<~P~attern:{{txtPattern}}>
{{type_description}}
<##Endian##~L~ittle:{{rLittle}}> <~B~ig:{{rBig}}> <B~o~th:{{rBoth}}>{{cGroup1}}>
<##Search backends##B~y~te search:{{opt0Bytes}}>
<~I~nstruction operands:{{opt1Insn}}>
<~M~icrocode:{{opt2Micro}}> <|> <Microcode ~r~eqmat:{{reqmat}}>
<Ctr~e~e:{{opt3Ctree}}> <|> <Ctree ~m~aturity:{{cmat}}>
<Pseu~d~ocode text:{{opt4Pseudo}}>{{cBackends}}>
<##Options##Match ~c~ase:{{chkCase}}>{{cOptions}}>
{{overview}}
{{patterns}}
""",
            {
                "txtPattern": F.StringInput(
                    value=default_query,
                ),
                "overview": F.StringLabel(
                    overview,
                    tp=F.FT_HTML_LABEL,
                ),
                "type_description": F.StringLabel("hic sunt descriptiones"),
                "FormChangeCb": F.FormChangeCb(self.OnFormChange),
                "patterns": F.StringLabel("Patterns:\n"),
                "cGroup1": F.RadGroupControl(["rLittle", "rBig", "rBoth"]),
                "reqmat": F.DropdownListControl(
                    items=[label for label, _ in self._reqmat_choices],
                    readonly=True,
                    selval=initial_reqmat_index,
                ),
                "cmat": F.DropdownListControl(
                    items=[label for label, _ in self._cmat_choices],
                    readonly=True,
                    selval=initial_cmat_index,
                ),
                # "pattern_type": F.DropdownListControl(
                #     items=[
                #         f"{p.name} ({', '.join([a for a in p.aliases if a])})"
                #         for p in parse.Types
                #     ],
                #     readonly=True,
                # ),
                "cBackends": F.ChkGroupControl(
                    ("opt0Bytes", "opt1Insn", "opt2Micro", "opt3Ctree", "opt4Pseudo"),
                    value=backends_mask & 0x1F,
                ),
                "cOptions": F.ChkGroupControl(
                    ("chkCase",),
                    value=options_mask & 0x01,
                ),
            },
        )

    def OnFormChange(self, fid):
        try:
            if fid == idaapi.CB_INIT:
                if not self._has_hexrays:
                    self.ShowField(self.opt2Micro, False)
                    self.ShowField(self.reqmat, False)
                    self.ShowField(self.opt3Ctree, False)
                    self.ShowField(self.cmat, False)
                    self.ShowField(self.opt4Pseudo, False)
                self.refresh()
            elif fid == self.txtPattern.id:
                self.refresh()
            elif fid in (self.rLittle.id, self.rBig.id, self.rBoth.id):
                self.refresh()
            # elif fid == self.pattern_type.id:
            #    ti = self.GetControlValue(self.pattern_type)
            #    self.SetControlValue(self.type_description, parse.Types[ti].description)
            #    self.refresh()
        except Exception:
            pass
        return 1

    def refresh(self):
        s = self.GetControlValue(self.txtPattern)
        cg = self.GetControlValue(self.cGroup1)
        endian = ["little", "big", "both"][cg]

        encodings = []
        for i in range(1, idaapi.get_encoding_qty()):
            encodings.append(idaapi.get_encoding_name(i))

        try:
            f = parse.PatternLocator.from_string(s, encodings=encodings, endian=endian)
            patterns = f.to_pattern()
            lines = []
            if len(patterns) == 1:
                lines.append("Pattern:")
            else:
                lines.append("Patterns:")
            lines.extend([str(p) for p in patterns])

            lines.append("")
            lines.append("Backend applicability:")
            lines.append("  Byte search: yes")
            lines.append(
                f"  Insn operand: {'yes' if f.to_operand_query() is not None else 'N/A'}"
            )
            if self._has_hexrays:
                lines.append(
                    f"  Microcode: {'yes' if f.to_microcode_query() is not None else 'N/A'}"
                )
                lines.append(
                    f"  CTree: {'yes' if f.to_ctree_query() is not None else 'N/A'}"
                )
                lines.append(
                    f"  Pseudocode: {'yes' if f.to_pseudocode_query() is not None else 'N/A'}"
                )

            msg = "\n".join(lines)
            self.enable_ok(True)

            endian_applicable = (
                f.type.category in [PatternCategory.signed, PatternCategory.unsigned]
                or f.type is parse.UnicodeString
            )
            self.ShowField(self.cGroup1, endian_applicable)

        except Exception as e:
            self.enable_ok(False)
            msg = f"Error: {e}"

        self.SetControlValue(self.patterns, msg)

    def enable_ok(self, enable: bool):
        pass

    def get_case_sensitive(self) -> bool:
        """Return whether 'Match case' is checked after Execute()."""
        return bool(self.cOptions.value & 1)

    def get_options_mask(self) -> int:
        """Return the options checkbox bitmask after Execute()."""
        return self.cOptions.value & 0x01

    def get_backends_mask(self) -> int:
        """Return the backend checkbox bitmask (bits 0-4) after Execute()."""
        return self.cBackends.value & 0x1F

    def get_reqmat(self) -> int:
        """Return the selected Hex-Rays maturity level for microcode search."""
        index = self.reqmat.value
        return self._reqmat_values[index]

    def get_cmat(self) -> int:
        """Return the selected Hex-Rays maturity level for ctree search."""
        index = self.cmat.value
        return self._cmat_values[index]

    def get_endian(self) -> str:
        return ["little", "big", "both"][self.cGroup1.value]

    def get_pattern(self) -> str:
        return self.txtPattern.value

    @staticmethod
    def test(execute=True):
        f = binary_search_form()
        f, args = f.Compile()

        if execute:
            ok = f.Execute()
        else:
            logger = __import__("logging").getLogger("ida-search")
            logger.info(args[0])
            logger.info(args[1:])
            ok = 0
        if ok == 1:
            value = f.txtPattern.value
            backends = f.get_backends_mask()
            endian = f.get_endian()
            logger = __import__("logging").getLogger("ida-search")
            logger.info("value=%s, backends=%#07b, endian=%s", value, backends, endian)
        f.Free()


if __name__ == "__main__":
    binary_search_form.test(execute=True)
